
// import { FooterWrapper } from "@/app/components/FooterWrapper";
// import type { Metadata } from "next";
// import { Questrial } from "next/font/google";
// import { HeaderWrapper } from "./components/HeaderWrapper";
// import "./globals.css";

// const questrial = Questrial({
//   subsets: ["latin"],
//   weight: "400",
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };



// export default async function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {

//   return (
//     <html lang="en" className={`${questrial.className} antialiased`}>
//       <body>
//         <HeaderWrapper />
//         {children}
//         <FooterWrapper />
//       </body>
//     </html>
//   );
// }
